### ISSUE TITLE
Add a link to http://codeforftl.org/ftlviz/ under projects

### ISSUE THREAD

**Issue by ryanvgates** [CodeForFtL/CodeForftL.github.io#19]
This will help new people navigate to this great project.

**Comment by qtrandev** [comment]
@ryanvgates Have any time to add this?

**Comment by ryanvgates** [comment]
@qtrandev yeah sure. What should we have the text read for the link? Fort Lauderdale Visualization? It's a bit generic.

**Comment by qtrandev** [comment]
Fort Lauderdale Traffic Visualization is fine

**Comment by qtrandev** [comment]
Looks good. Thanks!
