### ISSUE TITLE
Add information about Slack

### ISSUE THREAD

**Issue by qtrandev** [CodeForFtL/CodeForftL.github.io#23]
Add information to our website that we use Slack for communication.
To be added, attend a Meetup or email codeforftl gmail for more information.

**Comment by ryanvgates** [comment]
@qtrandev what portion of the site should this information go under? Contact?

**Comment by qtrandev** [comment]
Yes, the Contact section would be fine. Probably change the email address from Rob to codeforftl at gmail so emails go to Slack.

**Comment by ryanvgates** [comment]
@qtrandev I'm going to remove the reference and link to the old google groups discussion board and just paste in the slack information.

While I'm at it, I'm going to fix the alt text for your photo as well.

    <img src="images/quyenTran.png" class="img-circle" alt="Picture of Ryan Gates">

**Comment by ryanvgates** [comment]
@qtrandev I just made the updates, take a look and let me know what you think.

**Comment by qtrandev** [comment]
The changes look good.
