### ISSUE TITLE
Broken link to TED talk on codeforftl.org

### ISSUE THREAD

**Issue by FernanDoylet** [CodeForFtL/CodeForftL.github.io#32]
Link to "inspirational TED talk given by Jennifer Pahlka, the founder of Code for America" needs to be fixed.

**Comment by ryanvgates** [comment]
@FernanDoylet Thank you for pointing that out. Can you check the link again? It should be fixed now.

**Comment by FernanDoylet** [comment]
It works now, thanks.

**Comment by ryanvgates** [comment]
@FernanDoylet Thank you for pointing out this issue and submitting the pull request. I'm going to close this now.
